# Generated by Django 5.2.7 on 2025-11-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='SOLD',
            field=models.BooleanField(default=False),
        ),
    ]
