# Generated by Django 5.2.7 on 2025-11-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_products_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='SOLD',
            new_name='sold',
        ),
    ]
